/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Conference API
 * OpenAPI spec version: 1.0.0
 */
export interface CreateTalk {
  /**
     * @minLength 0
     * @maxLength 100
     */
  title: string;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
}

export interface Talk {
  id: number;
  title: string;
}

export type GetTalksResponse200 = {
  data: Talk[]
  status: 200
}

export type GetTalksResponseSuccess = (GetTalksResponse200) & {
  headers: Headers;
};
;

export type GetTalksResponse = (GetTalksResponseSuccess)

export const getGetTalksUrl = () => {




  return `https://localhost:7135/api/talks`
}

export const getTalks = async ( options?: RequestInit): Promise<GetTalksResponse> => {

  const res = await fetch(getGetTalksUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetTalksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as GetTalksResponse
}



export type CreateTalkResponse200 = {
  data: Talk
  status: 200
}

export type CreateTalkResponse400 = {
  data: ProblemDetails
  status: 400
}

export type CreateTalkResponse409 = {
  data: ProblemDetails
  status: 409
}

export type CreateTalkResponseSuccess = (CreateTalkResponse200) & {
  headers: Headers;
};
export type CreateTalkResponseError = (CreateTalkResponse400 | CreateTalkResponse409) & {
  headers: Headers;
};

export type CreateTalkResponse = (CreateTalkResponseSuccess | CreateTalkResponseError)

export const getCreateTalkUrl = () => {




  return `https://localhost:7135/api/talks`
}

/**
 * @summary Creates a talk
 */
export const createTalk = async (createTalkBody: CreateTalk, options?: RequestInit): Promise<CreateTalkResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateTalkUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTalkBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: CreateTalkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as CreateTalkResponse
}



export type GetTalkResponse200 = {
  data: Talk
  status: 200
}

export type GetTalkResponse404 = {
  data: ProblemDetails
  status: 404
}

export type GetTalkResponseSuccess = (GetTalkResponse200) & {
  headers: Headers;
};
export type GetTalkResponseError = (GetTalkResponse404) & {
  headers: Headers;
};

export type GetTalkResponse = (GetTalkResponseSuccess | GetTalkResponseError)

export const getGetTalkUrl = (id: number,) => {




  return `https://localhost:7135/api/talks/${id}`
}

export const getTalk = async (id: number, options?: RequestInit): Promise<GetTalkResponse> => {

  const res = await fetch(getGetTalkUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetTalkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as GetTalkResponse
}
