/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Conference API
 * OpenAPI spec version: 1.0.0
 */
export interface CreateTalk {
  /**
     * @minLength 0
     * @maxLength 100
     */
  title: string;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
}

export interface Talk {
  id: number;
  title: string;
}

export type talksGetTalksResponse200 = {
  data: Talk[]
  status: 200
}

export type talksGetTalksResponseSuccess = (talksGetTalksResponse200) & {
  headers: Headers;
};
;

export type talksGetTalksResponse = (talksGetTalksResponseSuccess)

export const getTalksGetTalksUrl = () => {




  return `https://localhost:7135/api/talks`
}

export const talksGetTalks = async ( options?: RequestInit): Promise<talksGetTalksResponse> => {

  const res = await fetch(getTalksGetTalksUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: talksGetTalksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as talksGetTalksResponse
}



export type talksCreateTalkResponse200 = {
  data: Talk
  status: 200
}

export type talksCreateTalkResponse400 = {
  data: ProblemDetails
  status: 400
}

export type talksCreateTalkResponse409 = {
  data: ProblemDetails
  status: 409
}

export type talksCreateTalkResponseSuccess = (talksCreateTalkResponse200) & {
  headers: Headers;
};
export type talksCreateTalkResponseError = (talksCreateTalkResponse400 | talksCreateTalkResponse409) & {
  headers: Headers;
};

export type talksCreateTalkResponse = (talksCreateTalkResponseSuccess | talksCreateTalkResponseError)

export const getTalksCreateTalkUrl = () => {




  return `https://localhost:7135/api/talks`
}

/**
 * @summary Creates a talk
 */
export const talksCreateTalk = async (createTalk: CreateTalk, options?: RequestInit): Promise<talksCreateTalkResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getTalksCreateTalkUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTalk)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: talksCreateTalkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as talksCreateTalkResponse
}



export type talksGetTalkResponse200 = {
  data: Talk
  status: 200
}

export type talksGetTalkResponse404 = {
  data: ProblemDetails
  status: 404
}

export type talksGetTalkResponseSuccess = (talksGetTalkResponse200) & {
  headers: Headers;
};
export type talksGetTalkResponseError = (talksGetTalkResponse404) & {
  headers: Headers;
};

export type talksGetTalkResponse = (talksGetTalkResponseSuccess | talksGetTalkResponseError)

export const getTalksGetTalkUrl = (id: number,) => {




  return `https://localhost:7135/api/talks/${id}`
}

export const talksGetTalk = async (id: number, options?: RequestInit): Promise<talksGetTalkResponse> => {

  const res = await fetch(getTalksGetTalkUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: talksGetTalkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as talksGetTalkResponse
}
