// This file is auto-generated by @hey-api/openapi-ts

export { type Options, talksCreateTalk, talksGetTalk, talksGetTalks } from './sdk.gen.js';
export type { ClientOptions, CreateTalk, ProblemDetails, Talk, TalksCreateTalkData, TalksCreateTalkError, TalksCreateTalkErrors, TalksCreateTalkResponse, TalksCreateTalkResponses, TalksGetTalkData, TalksGetTalkError, TalksGetTalkErrors, TalksGetTalkResponse, TalksGetTalkResponses, TalksGetTalksData, TalksGetTalksResponse, TalksGetTalksResponses } from './types.gen.js';
