// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { TalksCreateTalkData, TalksCreateTalkErrors, TalksCreateTalkResponses, TalksGetTalkData, TalksGetTalkErrors, TalksGetTalkResponses, TalksGetTalksData, TalksGetTalksResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const talksGetTalks = <ThrowOnError extends boolean = false>(options?: Options<TalksGetTalksData, ThrowOnError>): RequestResult<TalksGetTalksResponses, unknown, ThrowOnError> => (options?.client ?? client).get<TalksGetTalksResponses, unknown, ThrowOnError>({ url: '/api/talks', ...options });

/**
 * Creates a talk
 */
export const talksCreateTalk = <ThrowOnError extends boolean = false>(options: Options<TalksCreateTalkData, ThrowOnError>): RequestResult<TalksCreateTalkResponses, TalksCreateTalkErrors, ThrowOnError> => (options.client ?? client).post<TalksCreateTalkResponses, TalksCreateTalkErrors, ThrowOnError>({
    url: '/api/talks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const talksGetTalk = <ThrowOnError extends boolean = false>(options: Options<TalksGetTalkData, ThrowOnError>): RequestResult<TalksGetTalkResponses, TalksGetTalkErrors, ThrowOnError> => (options.client ?? client).get<TalksGetTalkResponses, TalksGetTalkErrors, ThrowOnError>({ url: '/api/talks/{id}', ...options });
