// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:7135/' | (string & {});
};

export type CreateTalk = {
    title: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type Talk = {
    id: number;
    title: string;
};

export type TalksGetTalksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/talks';
};

export type TalksGetTalksResponses = {
    /**
     * OK
     */
    200: Array<Talk>;
};

export type TalksGetTalksResponse = TalksGetTalksResponses[keyof TalksGetTalksResponses];

export type TalksCreateTalkData = {
    /**
     * The requestbody for the talk
     */
    body: CreateTalk;
    path?: never;
    query?: never;
    url: '/api/talks';
};

export type TalksCreateTalkErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type TalksCreateTalkError = TalksCreateTalkErrors[keyof TalksCreateTalkErrors];

export type TalksCreateTalkResponses = {
    /**
     * OK
     */
    200: Talk;
};

export type TalksCreateTalkResponse = TalksCreateTalkResponses[keyof TalksCreateTalkResponses];

export type TalksGetTalkData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/talks/{id}';
};

export type TalksGetTalkErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type TalksGetTalkError = TalksGetTalkErrors[keyof TalksGetTalkErrors];

export type TalksGetTalkResponses = {
    /**
     * OK
     */
    200: Talk;
};

export type TalksGetTalkResponse = TalksGetTalkResponses[keyof TalksGetTalkResponses];
